title: HXWD Test
description: A docusiste
remote_theme: carlosperate/jekyll-theme-rtd

# Theme settings:
site_author: Christian Wittern
repo_url: "https://github.com/tls-kr/tls-kr.github.io"
edit_on_github: true
github_docs_folder: true
sticky_navigation: true
prev_next_buttons_location: bottom
search_enabled: true
hljs_style: github-gist
